config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :claps
  resources :comments
  get 'pages/info'
  root 'ideas#index'
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clap.rb
class Clap < ApplicationRecord
    belongs_to :idea
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
    mount_uploader :picture, PictureUploader
    has_many :comments
    has_many :claps
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include Gravtastic
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/claps_controller.rb
class ClapsController < ApplicationController
  before_action :set_clap, only: [:show, :edit, :update, :destroy]

  # GET /claps
  # GET /claps.json
  def index
    @claps = Clap.all
  end

  # GET /claps/1
  # GET /claps/1.json
  def show
  end

  # GET /claps/new
  def new
    @clap = Clap.new
  end

  # GET /claps/1/edit
  def edit
  end

  # POST /claps
  # POST /claps.json
  def create
    @clap = Clap.new(clap_params)

    respond_to do |format|
      if @clap.save
        format.html { redirect_to idea_path(@clap.idea_id), notice: 'Clap was successfully created.' }
        format.json { render :show, status: :created, location: @clap }
      else
        format.html { render :new }
        format.json { render json: @clap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claps/1
  # PATCH/PUT /claps/1.json
  def update
    respond_to do |format|
      if @clap.update(clap_params)
        format.html { redirect_to @clap, notice: 'Clap was successfully updated.' }
        format.json { render :show, status: :ok, location: @clap }
      else
        format.html { render :edit }
        format.json { render json: @clap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claps/1
  # DELETE /claps/1.json
  def destroy
    @clap.destroy
    respond_to do |format|
      format.html { redirect_to claps_url, notice: 'Clap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clap
      @clap = Clap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clap_params
      params.require(:clap).permit(:user_name, :idea_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to idea_path(@comment.idea_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all.order(created_at: :desc)
    @cmtCount = 0
    @clapCount = 0
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @comments = @idea.comments.all
    @comment = @idea.comments.build
    @claps = @idea.claps.all
    @clap = @idea.claps.build
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claps_helper.rb
module ClapsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/claps/_form.html.erb
<%= form_for(@clap) do |form| %>
  <%= form.hidden_field :idea_id %>
  <%= form.hidden_field :user_name, :value => current_user.email %>
  <% if @clap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clap.errors.count, "error") %> prohibited this clap from being saved:</h2>

      <ul>
      <% clap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="cmt-tb">
    <tr>
      <td><%= form.submit("Clap", class: "btn-s")  %></td>
      <td><h2 class="clap-title">Clap to this post</h2></td>
    </tr>
  </table>
<% end %>

app/views/claps/edit.html.erb
<h1>Editing Clap</h1>

<%= render 'form', clap: @clap %>

<%= link_to 'Show', @clap %> |
<%= link_to 'Back', claps_path %>

app/views/claps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Claps</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Idea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claps.each do |clap| %>
      <tr>
        <td><%= clap.user_name %></td>
        <td><%= clap.idea_id %></td>
        <td><%= link_to 'Show', clap %></td>
        <td><%= link_to 'Edit', edit_clap_path(clap) %></td>
        <td><%= link_to 'Destroy', clap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clap', new_clap_path %>

app/views/claps/new.html.erb
<h1>New Clap</h1>

<%= render 'form', clap: @clap %>

<%= link_to 'Back', claps_path %>

app/views/claps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @clap.user_name %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @clap.idea_id %>
</p>

<%= link_to 'Edit', edit_clap_path(@clap) %> |
<%= link_to 'Back', claps_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.hidden_field :idea_id %>
  <%= f.hidden_field :user_name, :value => current_user.email %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2 class="clap-title">Comment to this post</h2>
   <table class="cmt-tb">
    <tr>
      <td><%= f.label :body %></td>
      <td><%= f.text_area :body %></td>
    </tr>
    <tr>
      <td></td>
      <td class="text-right"><%= f.submit("Send", :class => "btn-s")  %></td>
    </tr>
  </table>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Idea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.idea_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @comment.idea_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
    <% if idea.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>
            <ul>
                <% idea.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <h2 class="clap-title"><i>Name: </i></h2>
        <%= form.text_field :name %>
    </div>
    <div class="field">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description %>
    </div>

    <div class="field">
        <%= form.label :picture %>
        <%= form.file_field :picture, id: :idea_picture %>
    </div>

    <div class="actions">
        <%= form.submit("Send", class: "btn-s")  %>
    </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>
<div class="btn-s"><%= link_to 'Back', ideas_path %></div>

app/views/ideas/index.html.erb
<div class="timeline">
    <div>
        <h1 class="timeline-title">Timeline</h1>
        <div class="pageNav">
            <div class="pageNav-wrap cf">
                <a class="pageNav-item pageNav-item-1 is-current">All</a>
                <a class="pageNav-item pageNav-item-2">Your post</a>
                <div class="pageNav-line-long">
                    <div class="pageNav-line is-selected-1"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="timeline-body">
        <div class="cards">
            <div>
                <% @ideas.each do |idea| %>
                    <% @cmtCount = 0 %>
                    <% @clapCount = 0 %>
                    <div class="card">
                        <div class="btn-div">
                            <div class="btn-s"><%= link_to 'Show', idea %></div>
                            <div class="btn-s"><%= link_to 'Edit', edit_idea_path(idea) %></div>
                            <div class="btn-d"><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                        </div>
                        <div class="card_picFrom" style="cursor: pointer;">
                            <img src="../../images/bulb-money-flat.png">
                        </div>
                        <div class="card_left">
                            <div class="card_header">
                                <span class="card_name" style="cursor: pointer;"><i>Idea name: </i><%= idea.name %></span>
                            </div>
                            <div class="card_body">
                                <p><b>Post at:</b> <%= idea.created_at %></p>
                                <span><%= idea.description %></span>
                            </div>
                            <div>
                                <%= image_tag(idea.picture_url, width: 500) if idea.picture.present? %>
                            </div>
                            <div class="card_footer cf">
                                <% idea.claps.each do |clap| @clapCount += 1 end %>
                                <% idea.comments.each do |comment| @cmtCount += 1 end %>
                                <h3><i class="fa fa-comment" aria-hidden="true"></i><span class="clap_count"><%= @cmtCount %> comment(s) to this post!</span></h3>
                                <h3><img src="https://cdn2.iconfinder.com/data/icons/hand-gestures-7/400/Hands-12-512.png" style="width: 20px;"><span class="clap_count"><%= @clapCount %> clap(s) to this post!</span></h3>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="timeline-tail-appendable"></div>
    </div>
</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<div class="btn-s"><%= link_to 'Back', ideas_path %></div>

app/views/ideas/show.html.erb
<div class="btn-div-show">
    <div class="btn-s"><%= link_to 'Edit', edit_idea_path(@idea) %></div>
    <div class="btn-s"><%= link_to 'Back', ideas_path %></div>
    <div class="btn-d"><%= link_to 'Destroy', @idea, method: :delete, data: { confirm: 'Are you sure?' } %></div>
</div>
<p>
    <h2 class="clap-title"><i>Name: </i><%= @idea.name %></h2>
</p>
<p><b>Post at: </b><%= @idea.created_at %></p>
<p class="descript-idea">
    <%= @idea.description %>
</p>
<%= image_tag(@idea.picture_url, width: 300) if @idea.picture.present? %>
    <div class="col-md-11 col-md-offset-1">
        <h2 class="clap-title"><img src="https://cdn.iconscout.com/public/images/icon/free/png-512/clap-hand-medium-skin-tone-3443c3f08f57c977-512x512.png" style="width: 20px;"> Clap</h2>
        <% @claps.each do |clap| %>
            <div>
                <strong><%= clap.user_name %></strong> has clap to this post!
                <br />
            </div>
        <% end %>
    </div>
    <hr>
    <div class="col-md-11 col-md-offset-1">
        <h2 class="clap-title"><i class="fa fa-comment" aria-hidden="true"></i> Comments</h2>
        <% @comments.each do |comment| %>
            <div>
                <strong><%= comment.user_name %></strong> Post at: <%= comment.created_at %>
                <br />
                <p><%= comment.body %></p>
                <% if (current_user.email == comment.user_name) %>
                <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
                <% end %>
            </div>
        <% end %>
        <%= render 'claps/form' %>
        <%= render 'comments/form' %>
    </div>

app/views/pages/info.html.erb
<h2 class="clap-title">Welcome to my app!</h2>
<p>Hello World!!!</p>
<p>We make it awesome</p>